services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=60 #poll every 60 seconds
      - TZ=Europe/Berlin
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  oeb-nuxt-prod:
    image: openebench/openebench-nuxt-prod
    restart: always
    ports:
      - 4000:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  oeb-nuxt-dev:
    image: openebench/openebench-nuxt-dev
    restart: always
    ports:
      - 4001:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  oeb-nuxt-dev2:
    image: openebench/openebench-nuxt-dev2
    restart: always
    ports:
      - 4002:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  oeb-github-docs-frontend:
    image: openebench/oeb-github-docs-frontend
    restart: always
    ports:
      - 4100:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  oeb-legacy-prod:
    image: openebench/openebench-frontend-prod
    restart: always
    ports:
      - 4200:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  oeb-legacy-dev:
    image: openebench/openebench-frontend-dev
    restart: always
    ports:
      - 4201:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  oeb-legacy-dev2:
    image: openebench/openebench-frontend-dev-2
    restart: always
    ports:
      - 4202:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
